branch-defaults:
  default:
    environment: mozio-dev
    group_suffix: null
global:
  application_name: mozio
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
